export { default as AdminLayout } from './AdminLayout.vue'
export { IFrameRouterView } from './iframe'
export { useAdminTabbar } from './basic/tabbar'
export { buildAdminBreadcrumbPrefix, buildAdminBreadcrumbs } from './navigation/route-breadcrumb'
export type { AdminCurrentRouteRecord } from './navigation/route-breadcrumb'
export { closeAdminTab, createAdminTab, createAdminTabRecord, markActiveAdminTabs, upsertAdminTab } from './navigation/route-tab'
export { buildAdminMenuGroups, buildAdminMenus, markActiveAdminMenuGroups, markActiveAdminMenus } from './navigation/route-menu'
export { DEFAULT_ADMIN_TAB_STORAGE_KEY, useAdminTabStore } from './stores/index.ts'
export type { AdminNavigationRouteRecord as AdminBreadcrumbRouteRecord, AdminNavigationRouteNode as AdminRouteRecord } from '@monorepo-admin-core/types'
export type { BuildAdminMenuGroupsOptions, BuildAdminMenusOptions } from './navigation/route-menu'
