/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/access/menu-visible-403': RouteRecordInfo<
      '/access/menu-visible-403',
      '/access/menu-visible-403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/workbench': RouteRecordInfo<
      '/dashboard/workbench',
      '/dashboard/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/vite-plus': RouteRecordInfo<
      '/docs/vite-plus',
      '/docs/vite-plus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fallback/403': RouteRecordInfo<
      '/fallback/403',
      '/fallback/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/internal/audit': RouteRecordInfo<
      '/internal/audit',
      '/internal/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/jobs': RouteRecordInfo<
      '/monitor/jobs',
      '/monitor/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/sales': RouteRecordInfo<
      '/reports/sales',
      '/reports/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu': RouteRecordInfo<
      '/system/menu',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/params': RouteRecordInfo<
      '/system/params',
      '/system/params',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role': RouteRecordInfo<
      '/system/role',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings': RouteRecordInfo<
      '/system/settings',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | '/system/settings/notification'
      | '/system/settings/overview'
      | '/system/settings/theme'
    >,
    '/system/settings/notification': RouteRecordInfo<
      '/system/settings/notification',
      '/system/settings/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/overview': RouteRecordInfo<
      '/system/settings/overview',
      '/system/settings/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/theme': RouteRecordInfo<
      '/system/settings/theme',
      '/system/settings/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user': RouteRecordInfo<
      '/system/user',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/access/menu-visible-403.vue': {
      routes:
        | '/access/menu-visible-403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/workbench.vue': {
      routes:
        | '/dashboard/workbench'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/vite-plus.vue': {
      routes:
        | '/docs/vite-plus'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/fallback/403.vue': {
      routes:
        | '/fallback/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/internal/audit.vue': {
      routes:
        | '/internal/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitor/jobs.vue': {
      routes:
        | '/monitor/jobs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reports/sales.vue': {
      routes:
        | '/reports/sales'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/menu.vue': {
      routes:
        | '/system/menu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/params.vue': {
      routes:
        | '/system/params'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/role.vue': {
      routes:
        | '/system/role'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings.vue': {
      routes:
        | '/system/settings'
        | '/system/settings/notification'
        | '/system/settings/overview'
        | '/system/settings/theme'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/system/settings/notification.vue': {
      routes:
        | '/system/settings/notification'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings/overview.vue': {
      routes:
        | '/system/settings/overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings/theme.vue': {
      routes:
        | '/system/settings/theme'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/user.vue': {
      routes:
        | '/system/user'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
